// Asset URLs
export const AVATAR_PRESETS: Record<string, { id: string, displayName: string, style: string, image: string, palette: string[], texture: string, mood: string, defaultGreeting: string, type: 'preset' }> = {
  Hana: { 
    id: 'Hana', 
    displayName: 'Hana', 
    style: 'non-photorealistic', 
    image: new URL('./assets/hana.png', import.meta.url).href,
    palette: ['#2a3b52', '#8fa4b4', '#b53d3d'],
    texture: 'Soft studio gradient, matte fabric',
    mood: 'Studious, calm, disciplined',
    defaultGreeting: 'Hello. I am ready to assist you with your queries.',
    type: 'preset'
  },
  Ben: { 
    id: 'Ben', 
    displayName: 'Ben', 
    style: 'non-photorealistic', 
    image: new URL('./assets/ben.png', import.meta.url).href,
    palette: ['#344e52', '#5b6b4e', '#d4a38a'],
    texture: 'Deep mesh gradient, diffused light',
    mood: 'Friendly, modern, approachable',
    defaultGreeting: 'Hey there! Great to meet you. How can I help?',
    type: 'preset'
  },
  Carmen: { 
    id: 'Carmen', 
    displayName: 'Carmen', 
    style: 'non-photorealistic', 
    image: new URL('./assets/carmen.png', import.meta.url).href,
    palette: ['#2d5a9e', '#4a614d', '#c29a75'],
    texture: 'Blurred classroom, cork & slate textures',
    mood: 'Wise, nurturing, academic',
    defaultGreeting: 'Welcome. What knowledge shall we seek today?',
    type: 'preset'
  },
  Ingrid: { 
    id: 'Ingrid', 
    displayName: 'Ingrid', 
    style: 'photorealistic', 
    image: new URL('./assets/ingrid.png', import.meta.url).href,
    palette: ['#1e2a4a', '#d1d5db', '#a82e2e'],
    texture: 'Hard stone background, sharp suit lines',
    mood: 'Formal, authoritative, precise',
    defaultGreeting: 'Good day. Please state your inquiry.',
    type: 'preset'
  },
  Jay: { 
    id: 'Jay', 
    displayName: 'Jay', 
    style: 'photorealistic', 
    image: new URL('./assets/jay.png', import.meta.url).href,
    palette: ['#3f444d', '#d9c8b2', '#93c5fd'],
    texture: 'Corporate office blur, clean professional lines',
    mood: 'Executive, reliable, corporate',
    defaultGreeting: "Hello. Let's get down to business. What do you need?",
    type: 'preset'
  },
  Kai: { 
    id: 'Kai', 
    displayName: 'Kai', 
    style: 'non-photorealistic', 
    image: new URL('./assets/kai.png', import.meta.url).href,
    palette: ['#ca8a04', '#7dd3fc', '#4d7c0f'],
    texture: 'Overexposed bokeh, sunny park vibe',
    mood: 'Breezy, youthful, optimistic',
    defaultGreeting: "Hi! Awesome day, isn't it? What's up?",
    type: 'preset'
  },
  Kira: { 
    id: 'Kira', 
    displayName: 'Kira', 
    style: 'photorealistic', 
    image: new URL('./assets/kira.png', import.meta.url).href,
    palette: ['#254a65', '#9ca3af', '#fde68a'],
    texture: 'Industrial neutral, soft directional light',
    mood: 'Practical, grounded, industrious',
    defaultGreeting: "Hello. Let's get to work. How can I help?",
    type: 'preset'
  },
  Leo: { 
    id: 'Leo', 
    displayName: 'Leo', 
    style: 'non-photorealistic', 
    image: new URL('./assets/leo.png', import.meta.url).href,
    palette: ['#78350f', '#4338ca', '#facc15'],
    texture: 'Rustic, paint-splattered denim, warm clay',
    mood: 'Creative, artisanal, vintage',
    defaultGreeting: "Hey! Let's create something amazing today!",
    type: 'preset'
  },
  Paul: { 
    id: 'Paul', 
    displayName: 'Paul', 
    style: 'photorealistic', 
    image: new URL('./assets/paul.png', import.meta.url).href,
    palette: ['#334155', '#f8fafc', '#1e3a8a'],
    texture: 'Classic studio vignette, high-contrast formal',
    mood: 'Traditional, senior, dignified',
    defaultGreeting: 'Greetings. How may I be of service?',
    type: 'preset'
  },
  Piper: { 
    id: 'Piper', 
    displayName: 'Piper', 
    style: 'non-photorealistic', 
    image: new URL('./assets/piper.png', import.meta.url).href,
    palette: ['#0d9488', '#f59e0b', '#166534'],
    texture: 'Impressionist studio blur, floral & denim',
    mood: 'Artistic, vibrant, soulful',
    defaultGreeting: 'Hello! Excited to explore new ideas with you.',
    type: 'preset'
  },
  Sam: { 
    id: 'Sam', 
    displayName: 'Sam', 
    style: 'photorealistic', 
    image: new URL('./assets/sam.png', import.meta.url).href,
    palette: ['#92400e', '#14532d', '#bfdbfe'],
    texture: 'Blurred library shelves, warm textures',
    mood: 'Intellectual, smart-casual, cozy',
    defaultGreeting: 'Hi. Looking forward to a thoughtful conversation.',
    type: 'preset'
  },
  Vera: { 
    id: 'Vera', 
    displayName: 'Vera', 
    style: 'photorealistic', 
    image: new URL('./assets/vera.png', import.meta.url).href,
    palette: ['#000000', '#94a3b8', '#1e293b'],
    texture: 'Solid depth, metallic shimmer, luxury velvet',
    mood: 'Elegant, sophisticated, musical',
    defaultGreeting: 'Good day. It is a pleasure to assist you.',
    type: 'preset'
  },
};

export const VOICE_PRESETS: Record<string, { id: string, displayName: string, description: string }> = {
  kore: { id: 'kore', displayName: 'Kore', description: 'Firm' },
  orus: { id: 'orus', displayName: 'Orus', description: 'Firm' },
  autonoe: { id: 'autonoe', displayName: 'Autonoe', description: 'Bright' },
  umbriel: { id: 'umbriel', displayName: 'Umbriel', description: 'Easy-going' },
  erinome: { id: 'erinome', displayName: 'Erinome', description: 'Clear' },
  laomedeia: { id: 'laomedeia', displayName: 'Laomedeia', description: 'Upbeat' },
  schedar: { id: 'schedar', displayName: 'Schedar', description: 'Even' },
  achird: { id: 'achird', displayName: 'Achird', description: 'Friendly' },
  sadachbia: { id: 'sadachbia', displayName: 'Sadachbia', description: 'Lively' },
  fenrir: { id: 'fenrir', displayName: 'Fenrir', description: 'Excitable' },
  aoede: { id: 'aoede', displayName: 'Aoede', description: 'Breezy' },
  enceladus: { id: 'enceladus', displayName: 'Enceladus', description: 'Breathy' },
  algieba: { id: 'algieba', displayName: 'Algieba', description: 'Smooth' },
  algenib: { id: 'algenib', displayName: 'Algenib', description: 'Gravelly' },
  achernar: { id: 'achernar', displayName: 'Achernar', description: 'Soft' },
  gacrux: { id: 'gacrux', displayName: 'Gacrux', description: 'Mature' },
  zubenelgenubi: { id: 'zubenelgenubi', displayName: 'Zubenelgenubi', description: 'Casual' },
  sadaltager: { id: 'sadaltager', displayName: 'Sadaltager', description: 'Knowledgeable' },
  charon: { id: 'charon', displayName: 'Charon', description: 'Informative' },
  leda: { id: 'leda', displayName: 'Leda', description: 'Youthful' },
  callirrhoe: { id: 'callirrhoe', displayName: 'Callirrhoe', description: 'Easy-going' },
  iapetus: { id: 'iapetus', displayName: 'Iapetus', description: 'Clear' },
  despina: { id: 'despina', displayName: 'Despina', description: 'Smooth' },
  rasalgethi: { id: 'rasalgethi', displayName: 'Rasalgethi', description: 'Informative' },
  alnilam: { id: 'alnilam', displayName: 'Alnilam', description: 'Firm' },
  pulcherrima: { id: 'pulcherrima', displayName: 'Pulcherrima', description: 'Forward' },
  vindemiatrix: { id: 'vindemiatrix', displayName: 'Vindemiatrix', description: 'Gentle' },
  sulafat: { id: 'sulafat', displayName: 'Sulafat', description: 'Warm' },
  puck: { id: 'puck', displayName: 'Puck', description: 'Upbeat' },
  zephyr: { id: 'zephyr', displayName: 'Zephyr', description: 'Bright' },
};
